		insert into category(name) values ('Diary');
		insert into category(name) values ('Snacks');
		insert into category(name) values ('Drinks');
		insert into category(name) values ('Fruits');
		insert into category(name) values ('Vegetables');
		insert into category(name) values ('Cleaning');
		insert into category(name) values('Others');

	
		insert into product (name,price,quantity) values('Milk',2500,2000);
		insert into product (name,price,quantity) values('Eggs',2200,2000);
		insert into product (name,price,quantity) values('Butter',4000,3800);
		insert into product (name,price,quantity) values('Cheese',3000,2500);
		insert into product (name,price,quantity) values('Yogurt',1200,1000);
		insert into product (name,price,quantity) values('Candy',700,500);
		insert into product (name,price,quantity) values('Dried Fruit',1500,1000);
		insert into product (name,price,quantity) values('Popcorn',800,500);
		insert into product (name,price,quantity) values('Sunflower Seeds',1200,1100);
		insert into product (name,price,quantity) values('Tiger Beer',2500,2200);
		insert into product (name,price,quantity) values('Su Coffee',3500,3300);
		insert into product (name,price,quantity) values('Lemon Juice',3200,3000);
		insert into product (name,price,quantity) values('Red Bull',1000,700);
		insert into product (name,price,quantity) values('Red level',42000,40000);
		insert into product (name,price,quantity) values('Super Tea',300,250);
		insert into product (name,price,quantity) values('Aye thar yar Wine',4500,4000);
		insert into product (name,price,quantity) values('Apple',1500,1300);
		insert into product (name,price,quantity) values('Avocados',1500,1200);
		insert into product (name,price,quantity) values('Cherries',2000,1700);
		insert into product (name,price,quantity) values('Grapefruit',1500,1300);
		insert into product (name,price,quantity) values('Watermelon',2000,1800);
		insert into product (name,price,quantity) values('Broccoli',2000,1750);
		insert into product (name,price,quantity) values('Chilies',500,400);
		insert into product (name,price,quantity) values('Onions',3200,3000);
		insert into product (name,price,quantity) values('Potatoes',1000,1000);
		insert into product (name,price,quantity) values('Tomatos',1200,1100);
		insert into product (name,price,quantity) values('Air fresher',4000,3800);
		insert into product (name,price,quantity) values('Garbage bag',700,500);
		insert into product (name,price,quantity) values('Glass cleaner',1300,1200);
		insert into product (name,price,quantity) values('Dish soap',500,400);
		insert into product (name,price,quantity) values('Laundry soap',2200,2000);
		
			insert into product_cat(product_id,category_id) values(1,1);
		insert into product_cat(product_id,category_id) values(2,1);
		insert into product_cat(product_id,category_id) values(3,1);
		insert into product_cat(product_id,category_id) values(4,1);
		insert into product_cat(product_id,category_id) values(5,1);
		insert into product_cat(product_id,category_id) values(6,2);
		insert into product_cat(product_id,category_id) values(7,2);
		insert into product_cat(product_id,category_id) values(8,2);
		insert into product_cat(product_id,category_id) values(9,2);
		insert into product_cat(product_id,category_id) values(10,3);
		insert into product_cat(product_id,category_id) values(11,3);
		insert into product_cat(product_id,category_id) values(12,3);
		insert into product_cat(product_id,category_id) values(13,3);
		insert into product_cat(product_id,category_id) values(14,3);
		insert into product_cat(product_id,category_id) values(15,3);
		insert into product_cat(product_id,category_id) values(16,3);
		insert into product_cat(product_id,category_id) values(17,4);
		insert into product_cat(product_id,category_id) values(18,4);
		insert into product_cat(product_id,category_id) values(19,4);
		insert into product_cat(product_id,category_id) values(20,4);
		insert into product_cat(product_id,category_id) values(21,4);
		insert into product_cat(product_id,category_id) values(22,5);
		insert into product_cat(product_id,category_id) values(23,5);
		insert into product_cat(product_id,category_id) values(24,5);
		insert into product_cat(product_id,category_id) values(25,5);
		insert into product_cat(product_id,category_id) values(26,5);
		insert into product_cat(product_id,category_id) values(27,6);
		insert into product_cat(product_id,category_id) values(28,6);
		insert into product_cat(product_id,category_id) values(29,6);
		insert into product_cat(product_id,category_id) values(30,6);
		insert into product_cat(product_id,category_id) values(31,6);
		
		
	--	insert into product (name,dt_price,ws_price,category_id) values('Body Wash soap',2200,2000,null);
